### ISSUE TITLE
Sound key is high (tempo/pitch?)

### ISSUE THREAD

**Issue by thepulserifle** [MiSTer-devel/Arcade-Popeye_MiSTer#2]
The core released on 3/2/2020 appears to be playing the theme and all associated music in a "major" key. Higher than it should be.

Current core: https://www.youtube.com/watch?v=61526OXoSYU

Expected sound: https://www.youtube.com/watch?v=hErObuqvlHs

You can really hear this in the main theme and the collection of hearts. It all seems too sharp, too high.

**Comment by sorgelig** [comment]
fixed in new release
